### ISSUE TITLE
travis builds fails silently

### ISSUE THREAD

**Issue by keszybz** [TurboGears/sprox#6]
See https://travis-ci.org/TurboGears/sprox/jobs/70931120 . Various tests fail but the checks are marked as passing.

**Comment by amol-** [comment]
That's know, they are actually doctests which are not maintained nor supported since years.

As doctests are based on string comparison they start to fail every time ToscaWidgets changes even a space in their templates or the template engine itself changes something minor (like order of attributes of a tag). So they have not been maintained anymore for the past years.

doctests were a good idea that revealed to be impractical

**Comment by pedersen** [comment]
Suggestion: Should those tests just be removed then? If they're not
actually providing value, I'd say to get rid of them specifically to avoid
this sort of question.

**Comment by amol-** [comment]
Yeah, I was thinking of fixing them one last time (as TW2 has not received major changes since 2.2) and if they break again just remove them.

**Comment by amol-** [comment]
Got them back in place and changed test_doctest to fail if any of the doctests fails: https://github.com/TurboGears/sprox/commit/2c10362f1c80c937dec207905cf0588b192a6877

**Comment by keszybz** [comment]
Great, thanks!
